### ISSUE TITLE
Error: Cannot fund module when attempting to bundle JS files

### ISSUE THREAD

**Issue by eoghanoh1** [hugabor/bundle-js#10]
Hi,

Seeing an error when attempting to bundle up JS files. From the trace in the command line console, it looks like the error is from the resolve library, 'Error: Cannot fund module'. 
Please see attached command line screen grab.

The testWrapper.js file that is being resolved is not in in my project, unsure where this reference is coming from. It is strange because the path referenced for this file, is the path to my project directory.

Any ideas what could be wrong?

![libraryversions](https://user-images.githubusercontent.com/17784668/33185142-9440a51c-d078-11e7-8af1-f0ebbd1222fb.PNG)
![moduleresolveerror](https://user-images.githubusercontent.com/17784668/33185150-97685c8a-d078-11e7-9e55-649004622f82.PNG)

Thanks,
Eoghan

**Comment by hugabor** [comment]
Bundle-js depends on the [resolve](https://www.npmjs.com/package/resolve) module to find dependencies. The _resolve_ module mimics the behavior of NodeJS's module resolution algorithm.

You might be trying to reference `testWrapper.js` without a file extension perhaps? References to files within your project have to include the file extension I believe.

Thanks

**Comment by mvillalobosj** [comment]
https://github.com/hugabor/bundle-js/blob/master/index.js#L38

It's coming from this line in your index.js file @hugabor

**Comment by hugabor** [comment]
Thanks for the catch! Will publish in a few days.
