### ISSUE TITLE
`// include` not working

### ISSUE THREAD

**Issue by Shizen** [hugabor/bundle-js#15]
Simple to reproduce.  i made two files...

a.js:  
```js
// jshint esversion:6

// This is file A

let a = "something great";

// include ./b.js

console.log(`${a} is ${b}.`);
```

b.js:  
```js
// jshint esversion:6

let b = "a test for great testification";
```

`include_b` and `require` work as expected, but `include` is ignored.  Executing `.\node_modules\.bin\bundle-js .\lib\a.js` from the command line produces the file...

output.js:  
```js
// jshint esversion:6
// This is file A
let a = "something great";
// include ./b.js
console.log(`${a} is ${b}.`);
```

**Comment by sstadlberger** [comment]
I'm having the same issue here. I'm using a fresh install of Node v10.15.1.

**Comment by hugabor** [comment]
@Shizen @sstadlberger 
Fixed! The issue was that the `include_b` check was made after the `include` check using the original file, not the file with the includes already in it.

**Comment by sstadlberger** [comment]
@hugabor Thanks, that fixed it :-)
