### ISSUE TITLE
Doesn't support circular dependencies

### ISSUE THREAD

**Issue by calda** [hugabor/bundle-js#7]
Please fix

**Comment by hugabor** [comment]
There is no plan to implement support for circular dependencies. You're welcome to submit a pull-request, but this feature is most likely not within the scope of this module.

**Comment by calda** [comment]
I present this code, which after executing guarantees that your dependency graph will not have any circular dependencies. 
```
    while dag.isCircular {
         dag.removeEdge(dag.edges.random)
    }
````

**Comment by calda** [comment]
I'd also like to note that the above algorithm has a best-case runtime of `O(1)` and a worst-case runtime of `O(E)`. This means it is very efficient, especially for small dependency graphs. I recommend adding it to your library.
